### PR TITLE
Ribogrid plot 68

### PR DESCRIPTION
**Pull request by FlicAnderson**
This branch (ribogrid-plot-68) contains Edward's new ribogrid plot, as well as styling and minor refactoring of generate_stats_figs.R. 

Develop branch (last commit db73b2e8) was merged into ribogrid-plot-68.

Regression tests run OK, exit code tests OK before and after merging develop.

Additional refactoring of generate_stats_figs.R is still required, and I'd advise doing this in separate branch referring to issue #32

### CODE REVIEW

**Comment by mikej888** [comment]
@FlicAnderson 

I've commited a change to develop to riboviz/test/regression/test_vignette.py with a new test_output_pdf(expected, riboviz_run, prefix, content) function which checks for the existence of PDFs of a given name in both the expected and actual outputs from a given run. Please merge in the current version of develop and update `riboviz/test/regression/test_vignette.py`'s `test_output_pdf` function to check for the additional grid and bar plots.

Please update docs/run-vignette.md,

* In the list of output files following `For each of these names ...` (line 125), add the new files output.
* At the end of `## Anatomy of prep_riboviz.py` section, in the `Outputs files ...` section (line 734), add the new files output.

Please update docs/developer.md `## Coding style` and add use of lintR and styleR. If these need to be installed then add a new section at the top of the file (this is v. useful, I was wondering what style checking tools existed for R)

Once done it'll be ready to merge, then I'll run and create a new data bundle to deposit on DataSync for future regression test runs.

More generally, at some point documentation of the R functions would be useful (across all the R scripts). The following resources may be of use:

* http://r-pkgs.had.co.nz/man.html#man-functions
* https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html
* https://www.r-bloggers.com/the-need-for-documenting-functions/

**Comment by FlicAnderson** [comment]
@mikej888 I've changed those things you've mentioned, and *I think* have made the correct edits to test_vignette.py.  

The regression test breaks when run now (using current test folder of 4f28def), giving "4 failed, 59 passed", and as we've got 4 new files, I think that's a good sign!  It points to the new pdfs and gives "AssertionError: Non-existent file" errors, so I think this is expected.  

The exit code test still passes 5/5, so I think all is well otherwise.

**Comment by FlicAnderson** [comment]
I haven't currently included the R function documentation here, and can either create this as a separate issue or combine in alongside the push to resolve #32 - what is best, do you think?

**Comment by ewallace** [comment]
Best to do the documentation and refactoring together in #32, I think. We will need to strip many functions out of `generate_stats_figs.R` and put them into their own files. So we should separate that from the currently question, which is about adding functionality and fixing style.

**Comment by mikej888** [comment]
@FlicAnderson there was a typo (a misplaced comma) in test_vignette.py which I've corrected, but everything else was fine, thanks!

**Comment by mikej888** [comment]
I've added a new regression test ZIP file vignette-20191015-bbba3c5.zip, to DataSync.

**Comment by FlicAnderson** [comment]
Thanks for the comma catch and for packaging up the new regression file bundle.

**Comment by mikej888** [comment]
@flic to close if happy this is complete.

**Pull request merged**
