### PR TITLE
Generalise regression test vignette 155

### PR DESCRIPTION
**Pull request by mikej888**

### CODE REVIEW

**Comment by ewallace** [comment]
The commit message for e7f953a on "remove NotHere-tagged sample regardless" has me worried. Are we still testing that the pipeline "fails right" with an informative error message if samples are missing? This is an important use-case because it is very easy to mis-spell file names, so we need to tell users if they have asked to analyse an input file that isn't there.

Apologies if I missed something here.

**Comment by mikej888** [comment]
The pipeline does not fail if one or more samples are missing as it needs to continue on and process the samples that do exist. It does print an error message about any missing files:

```console
$ python -m riboviz.tools.prep_riboviz -c vignette/vignette_config.yaml -d
...
Processing samples
Processing sample: WTnone
Processing file: vignette/input/SRR1042855_s1mi.fastq.gz
...
Processing sample: WT3AT
Processing file: vignette/input/SRR1042864_s1mi.fastq.gz
...
File not found: vignette/input/example_missing_file.fastq.gz
Finished processing 3 samples, 1 failed
Collate TPMs across sample results. Log: vignette/logs/20200507-044040/collate_tpms.log
Count reads. Log: vignette/logs/20200507-044040/count_reads.log
Completed
```

However, if _all_ the samples are missing then the pipeline does fail with a suitable exit code. That is tested via `riboviz.test.tools.test_prep_riboviz`.

For the regression tests, which the commit relates to, `vignette_config.yaml` is used as-is with `NotHere`. However, the sample names are then used, in conjunction with pytest's fixtures functionality, to auto-generate test functions for each sample-specific file. If `NotHere` was present then the result would be myriad test functions that try and validate, for example `tmp/NotHere/trim.fq`, `output/NotHere/tpms.csv` and many others, all of which fail as they don't exist. So `NotHere` is removed so no test functions for non-existent files are created.

**Comment by ewallace** [comment]
Thanks for clearing up my misunderstanding.

**Comment by FlicAnderson** [comment]
As detailed [HERE](https://github.com/riboviz/riboviz/issues/155#issuecomment-637740928), I've tested this on real-size dataset, checked it picks up 'introduced' differences, merged the latest develop into it, checked regression tests on this branch, other tests and coverage. 

All good, so I'm going to merge PR.

**Comment by mikej888** [comment]
@FlicAnderson thanks for checking it on a full size dataset and merging the PR!

**Pull request merged**
