### PR TITLE
H5 open 106

### PR DESCRIPTION
**Pull request by FlicAnderson**
Fix for issue #106 as detailed complete here: https://github.com/riboviz/riboviz/issues/106#issuecomment-621225688 

Passes regression test: 72 passed in 222.70 seconds (with `--check-index-tmp`; so these are all ok).

Passes all tests excluding regression: 165 passed in 149.97 seconds

### CODE REVIEW

**Comment by FlicAnderson** [comment]
As part of [this commit cb8773d](https://github.com/riboviz/riboviz/pull/170/commits/cb8773dde6731d9e28bc76773860d2ac38e15b68), I added R package `{here}` to the install documentation as this is used in test script `test_h5-open-106.R`; was also missing a `library("here")` call in that script, as it's used to easily source `generate_stats_figs.R`. 

Note: as part of some of the changes in #32 refactoring, use of the `{here}` package will also be used to resolve some of the hard-coding of directory names in the temporary 'interactive' fix in lines 19-32 in `generate_stats_figs.R` in this branch which allows debugging. Just FYI.

Tests redone for completeness: 

Passes regression test: 72 passed in 219.54 seconds (with --check-index-tmp; so these are all ok).

Passes all tests excluding regression: 165 passed in 147.95 seconds

**Comment by mikej888** [comment]
For `rscripts/generate_stats_figs.R` the line:

```
hdf5file <- hd_file # filehandle for the h5 file
```

seems redundant as both variables have the same value.

For
```
GetGeneReadLength <- function(gene, hdf5file){
  rhdf5::h5readAttributes(hd_file, name=paste0("/", gene, "/", dataset, "/reads"))[["reads_by_len"]]
}
```
`hdf5file` seems never to be used. Instead, `hd_file` is used. And similarly in other functions.

`rscripts/test_h5-open-106.R` seems branch-specific, and you-specific. It's hard to see how someone else would use or maintain this, so, if it's your personal tests it could be removed.

When merged into "develop" please ping the team that they need to install  R "here" before using the most recent version.

**Comment by FlicAnderson** [comment]
As of commit `cb2f2468c`, branch `h5-open-106` passes the regression tests (42 passed, 30 tmp/index skipped, against `regression-test-data-20200221`). 

Changes made from Mike's suggestion [here](https://github.com/riboviz/riboviz/pull/170#issuecomment-624716850) to swap out hdf5file for hd_file as this is what's being used anyway (and is the variable fed-in to the script), and the rough test script has been removed for the merge.

**Comment by FlicAnderson** [comment]
Merged develop (last commit: 63241663f) into h5-open-106, rechecked vignette runs and regression tests pass:  all good!

**Pull request merged**
