### PR TITLE
Change yeast codon pos i200, fixes #194

### LINKED ISSUE #194: Change data input file yeast_codon_pos_i200.RData to alternative file format
This was discussed as part of the pull request #184 on the way to close issue #32, so I'm opening this as a ticket since it probably needs a bit of investigation anyway, regardless of how I navigate this in closing #184 

The file: yeast_codon_pos_i200.RData 

Initial issue details here: https://github.com/riboviz/riboviz/pull/184#issuecomment-652469274 

It'd be handy to change this from a specific R data file to something easier to interrogate.

### PR DESCRIPTION
**Pull request by ewallace**
I made some updates to @shahpr 's edits here; I'm ready to merge if he approves.

### CODE REVIEW

**Comment by mikej888** [comment]
The header of `data/yeast_codon_table.tsv` is
```
Gene	PosCodon	Codon
```
But header of the former `data/yeast_codon_pos_i200.tsv` was:
```
Gene	Codon	Pos
```
The latter was chosen to be consistent with the output of the `riboviz/tools/get_cds_codons.py` (which invokes functions in `riboviz/get_cds_codons.py`. 

To resolve this, either change `PosCodon` to `Pos` or change `POS = "Pos"` in `riboviz/get_cds_codons.py` to `POS = "PosCodon"`.

It would be useful also to update `docs/reference/data.md`, section `## Additional yeast-specific data` with information on how `yeast_codon_table.tsv` was created.

**Comment by ewallace** [comment]
Thanks! I have updated `riboviz/get_cds_codons.py` in this branch as suggested. It's still work in progress as I did not test the output yet.

**Comment by ewallace** [comment]
I tested the output of `riboviz/tools/get_cds_codons.py` on the `tiny_2genes_20utrs` example:
```
python -m riboviz.tools.get_cds_codons \
        -f ../example-datasets/simulated/mok/annotation/tiny_2genes_20utrs.fa \
        -g ../example-datasets/simulated/mok/annotation/tiny_2genes_20utrs.gff3
```

The output looks great:

```
# Created by: RiboViz
# Date: 2021-03-10 22:11:45.847458
# Command-line tool: /Users/edwardwallace/Repos/riboviz/riboviz/riboviz/tools/get_cds_codons.py
# File: /Users/edwardwallace/Repos/riboviz/riboviz/riboviz/get_cds_codons.py
# Version: commit ffc0dafe7a8e4c501a362e41ddd67145ba44b3bb date 2021-03-10 19:38:38+00:00
Gene    PosCodon        Codon
MAT     1       ATG
MAT     2       GCC
MAT     3       ACA
MAT     4       TGA
MIKE    1       ATG
MIKE    2       ATC
MIKE    3       AAG
MIKE    4       GAG
MIKE    5       TAA
```

I also checked that  
```
python -m riboviz.tools.get_cds_codons \
        -f data/yeast_CDS_w_250utrs.fa \
        -g data/yeast_CDS_w_250utrs.gff3 \
        -c data/yeast_codon_table_alternative.tsv
```
produces identical table output to `data/yeast_codon_table.tsv`.

Do we need to create any automated tests out of these?

**Comment by mikej888** [comment]
There are already automated tests. Run:
```console
$ pytest  riboviz/test/test_check_fasta_gff.py 
```

**Comment by ewallace** [comment]
Thanks for explaining, tests passed:

```
$ pytest  riboviz/test/test_check_fasta_gff.py 
============================================ test session starts ============================================
platform darwin -- Python 3.7.9, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/edwardwallace/Repos/riboviz/riboviz
collected 23 items                                                                                          

riboviz/test/test_check_fasta_gff.py .......................                                          [100%]

============================================ 23 passed in 14.34s ============================================
```

I am ready to merge this pull request - any more feedback first?

I didn't find documentation on regression tests for those functions - did I miss something or do we need a new issue ticket? I was thinking an introductory section in [docs/developer/testing.md](docs/developer/testing.md) briefly explaining to the confused the components of the testing system. And something in the developer guide about testing python tools - even that aren't part of the nextflow workflow - as requirement for a pull request.

**Comment by mikej888** [comment]
> I didn't find documentation on regression tests for those functions - did I miss something or do we need a new issue ticket? 

Your use of the unit tests to check that the tests still pass after your changes was the regression test. It is not the tests themselves that make them regression tests but how they are used. 

I think I may have introduced this confusion with our "regression tests" (`riboviz.test.regression`) which we do use primarily as regression tests but which would perhaps be more accurately termed "system tests".

> I was thinking an introductory section in docs/developer/testing.md briefly explaining to the confused the components of the testing system.
> And something in the developer guide about testing python tools - even that aren't part of the nextflow workflow - as requirement for a pull request.

Yes, this could be better structured and can also cover what tests should be rerun (as regression tests) and when.

**Comment by ewallace** [comment]
@mikej888 I have lost track here. Are you happy to merge this branch now?

**Comment by mikej888** [comment]
Yes that's fine!

**Comment by ewallace** [comment]
Thanks - I had just lost track.

**Pull request merged**
